name: Java CI with Maven and Docker Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'action.txt'
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'  # 根据你的项目需求选择合适的Java版本
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package -DskipTests

    # 确保Maven构建的artifacts在Docker构建上下文中可用
    - name: Prepare artifacts for Docker build
      run: |
        mkdir -p .docker-artifacts
        cp server/target/kkFileView-*.tar.gz .docker-artifacts/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        target: app
        push: true
        tags: xjxjin/kkfileview:latest
        platforms: linux/amd64,linux/arm/v7,linux/arm64
